bio/bio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("dashboard.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

bio/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path('', views.home, name="home"),
    path('logout', views.logout_view, name='logout'),
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('runs/', views.RunListView.as_view(), name='runs'),
    path('reports/', views.ReportListView.as_view(), name='reports'),
    path('reservoirs', views.ReservoirListView.as_view(), name='reservoirs'),
    path('compare_runs', views.compare_runs, name='compare_runs'),
    path('device/<int:pk>', views.DeviceDetailView.as_view(), name='device-detail'),
    path('run/<int:pk>', views.RunDetailView.as_view(), name='run-detail'),
    path('report/<int:pk>', views.ReportDetailView.as_view(), name='report-detail'),
    path('<int:run_id>/test/', views.test, name="test"),
]

bio/dashboard/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Device(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    serial_number = models.CharField(max_length=20)
    storage = models.CharField(max_length=30, null=True, blank=True)
    notes = models.CharField(max_length=30, null=True, blank=True)
    ip = models.CharField(max_length=40, null=True, blank=True)
    filter = models.CharField(max_length=40, null=True, blank=True)
    tempsensor = models.CharField(max_length=40, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('dashboard:device-detail', args=[str(self.id)])

    def __str__(self):
        return self.name + " " + self.serial_number


class Reservoir(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    assembly_date = models.DateField(null=True, blank=True)
    serial_number = models.IntegerField(null=False, unique=True)
    vendor = models.CharField(max_length=200)
    substrate = models.CharField(max_length=200)
    cleaning = models.CharField(max_length=200)
    coating = models.CharField(max_length=200)
    functionalization = models.CharField(max_length=200)
    library = models.CharField(max_length=200)
    blocking = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('dashboard:reservoir-detail', args=[str(self.id)])

    def __str__(self):
        return str(f"{self.serial_number} {self.substrate} {self.functionalization} {self.library}")


class Run(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, unique=True)
    device = models.ForeignKey(Device, null=True, blank=True, on_delete=models.SET_NULL)
    operator = models.CharField(max_length=50, null=True, blank=True)
    sequencing_protocol = models.CharField(max_length=100, null=True, blank=True)
    path = models.CharField(max_length=200, null=True)
    started_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=400, null=True, blank=True)
    reservoir = models.ForeignKey(Reservoir, null=True, blank=True, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('dashboard:run-detail', args=[str(self.id)])

    def __str__(self):
        return self.name



class Report(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    run = models.ForeignKey(Run, null=True, blank=True, on_delete=models.SET_NULL)
    path = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
    )

    def get_absolute_url(self):
        return reverse('dashboard:report-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

bio/dashboard/forms.py
from django import forms
from .models import Report


class RoiSetForm(forms.Form):
    title = forms.CharField(label='Label', max_length=50)
    file = forms.FileField(label='RoiSet File')


class ExampleModelForm(forms.Form):
    report1 = forms.ModelChoiceField(
        label="Report 1",
        queryset = Report.objects.all(),
        required=True
    )

    report2 = forms.ModelChoiceField(
        label="Report 2",
        queryset = Report.objects.all(),
        required=False
    )

    report3 = forms.ModelChoiceField(
        label="Report 3",
        queryset = Report.objects.all(),
        required=False
    )

    report4 = forms.ModelChoiceField(
        label="Report 4",
        queryset = Report.objects.all(),
        required=False
    )

    report5 = forms.ModelChoiceField(
        label="Report 5",
        queryset = Report.objects.all(),
        required=False
    )

    report6 = forms.ModelChoiceField(
        label="Report 6",
        queryset = Report.objects.all(),
        required=False
    )

bio/dashboard/views.py
from typing import List, AnyStr

from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

from django.http import HttpResponse
from django.views import generic
from .models import Device, Run, Report, Reservoir
import pandas as pd
from plotly.offline import plot
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import os
import glob
import math
from itertools import product
import ziontools
from sklearn import linear_model
import cv2 as cv
from scipy import ndimage
import roifile
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import re
from datetime import datetime, timedelta
from django.utils import timezone
import dateutil.parser
from .tasks import run_pixel_extraction, mul
from .forms import RoiSetForm, ExampleModelForm
import itertools

from django.http import HttpResponseRedirect
from django.urls import reverse

# TODO, move to configuration
data_root_path = "/static_root/InstrumentData"
sequencing_file = '/tmp/Sequencing.csv'
reservoir_file = '/tmp/Reservoir_Inventory.csv'




def extract_datetime(subfolderstr: str) -> str | None:
    """TODO timestamp needs to be provided in iso format instead of being extracted from folder name"""
    match = re.search(r'^(20\d{2})(\d{2})(\d{2})_(\d{2})(\d{2})', subfolderstr)

    if not match:
        print(f'unable to extract datetime from {subfolderstr}')
        return None

    # print(type(match))
    # print(match.groups())
    # print(match.group(0))

    datetime_str = match.group(0)  # 20230612_1145
    datetime_object = datetime.strptime(datetime_str, '%Y%m%d_%H%M')
    # print(datetime_object) # 2023-06-12 11:45:00

    aware_start_time = timezone.make_aware(datetime_object)  # aware

    return aware_start_time


def update_run_start_date():

    runs = Run.objects.all()
    for run in runs:
        if not run.started_at:
            d = extract_datetime(run.name)
            if d:
                run.started_at = d
                run.save()


def import_signup_sheet():

    if not os.path.exists(sequencing_file):
        print(f"{sequencing_file} not found")
        return

    df = pd.read_csv(sequencing_file)
    # drop rows that are fully empty
    df.dropna(how="all", inplace=True)

    for index, row in df.iterrows():
        print(row)

        # search runs for Seq ID
        # filter out QC
        # check if transformer matches, if not print error
        # update reservoir if not set, print error if different
        # add to notes: Scientist	Seq Ctrl Program	Description	Deviations

        runs = Run.objects.filter(name__contains=row['Seq ID'])

        # update() only works on querysets,
        if runs:
            print("type of run", type(runs))
            runs.update(notes=row['Description'])
            runs.update(operator=row['Scientist'])
            runs.update(sequencing_protocol=row['Seq Ctrl Program'])
            match = re.search("^R(\d{1,4})$", str(row['Reservoir']))
            if match:
                reservoir_sn = int(match.group(1))
            else:
                print(f"skip {row['Reservoir']}")
                continue
            reservoir = Reservoir.objects.filter(serial_number=reservoir_sn)
            print('received object', reservoir)
            if reservoir:
                print('run update')
                runs.update(reservoir=reservoir[0])  # TODO, make sure it is unique


def import_reservoirs_from_csv():

    if not os.path.exists(reservoir_file):
        print(f"{reservoir_file} not found")
        return

    df = pd.read_csv(reservoir_file)

    # show bad entries
    #df.dropna(subset=['Unnamed: 16'])

    # drop unnamed columns
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # drop rows that are fully empty
    df.dropna(how="all", inplace=True)

    '''
    created_at = models.DateTimeField(auto_now_add=True)
    serial_number = models.IntegerField(null=False, unique=True)
    vendor = models.CharField(max_length=200)
    substrate = models.CharField(max_length=200)
    cleaning = models.CharField(max_length=200)
    coating = models.CharField(max_length=200)
    functionalization = models.CharField(max_length=200)
    library = models.CharField(max_length=200)
    blocking = models.CharField(max_length=200)
    '''

    for index, row in df.iterrows():
        print(row)

        reservoir_sn = int(row['ID'])

        assembly_date = None
#        print(f"date: {row['Assembly Date']} type: {type(row['Assembly Date'])}")
        if isinstance(row['Assembly Date'], float):
            print(f"skip reservoir {reservoir_sn}, assembly_date is float: {row['Assembly Date']}")
        else:
            assembly_date = dateutil.parser.parse(row['Assembly Date'])

        reservoirs = Reservoir.objects.filter(serial_number=reservoir_sn)
        if reservoirs.exists():
#            reservoirs.update(assembly_date=assembly_date)
            continue

        r = Reservoir(
            assembly_date=assembly_date,
            serial_number=reservoir_sn,
            vendor=row['Slide Vendor'],
            substrate=row['Substrate'],
            cleaning=row['Cleaning'],
            coating=row['Coating'],
            functionalization=row['Functionalization'],
            library=row['SpotLayout#']
#            blocking=models.CharField(max_length=200)
        )
        r.save()


def scan():

    if not os.path.isdir(data_root_path):
        print(f"error with: {data_root_path}")
        return

    devices = Device.objects.all()

    for dev in devices:
        print(dev.name)

        raw_device_path = os.path.join(data_root_path, dev.name)
        if os.path.isdir(raw_device_path):

            subfolders: list[AnyStr] = [f.path for f in os.scandir(raw_device_path) if f.is_dir()]

            for subfolder in subfolders:
                run_directory = os.path.basename(subfolder)
                print(run_directory)

                # guess number of cycles:
                prot_file_names = sorted(glob.glob(subfolder + "/*Protocol*", recursive=False))
                if prot_file_names:
                    print(prot_file_names[-1])

                if Run.objects.filter(name=run_directory).exists():
                    # run exists already
                    continue

                # extract date from subfolder, TODO, should be in a json file, in ISO format
                started_at = extract_datetime(run_directory)

                r = Run(
                    name=run_directory,
                    device=Device.objects.get(name=dev.name),
                    path=subfolder.lstrip('/static_root'),
                    started_at=started_at,
#                    notes="test",
#                    reservoir=Reservoir.objects.get(serial_number=366),
                )
                print(f"Create new run {r}")
                r.save()

    '''

    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    device = models.ForeignKey(Device, null=True, blank=True, on_delete=models.SET_NULL)
    path = models.CharField(max_length=200, null=True)
    started_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=400, null=True)
    reservoir = models.ForeignKey(Reservoir, null=True, blank=True, on_delete=models.SET_NULL)

    '''

@login_required
def home(request):
    devices = Device.objects.all()

    scan()
#    update_run_start_date()
#    import_reservoirs_from_csv()
    import_signup_sheet()

    run_histogram = create_run_histogram()
    return render(request, 'home.html', {'devices': devices, 'run_histogram': run_histogram})


def logout_view(request):
    logout(request)
    return redirect('dashboard:home')


@login_required
def compare_runs(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = ExampleModelForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            df_reports = {}

            for i in range(1, 7):
                report = form.cleaned_data["report"+str(i)]
                if not report:
                    continue
                report_full_path = os.path.join("/static_root", report.path)
                spot_data_csv = os.path.join(report_full_path, 'spot_pixel_data.csv')
                if os.path.exists(spot_data_csv):
                    df_i = pd.read_csv(spot_data_csv)
                    df_reports[report.name] = df_i

            df = pd.concat(df_reports).reset_index()
            df.rename(columns={'level_0': 'report', 'level_1': 'old_index'}, inplace=True)

            plots = []
            # for all spot names:
            for spot_name in df.spot_name.unique():
                dfs = df.loc[(df['spot_name'] == spot_name) & (df['cycle'] == 1)] # cycle check may not be necessary, always cycle 1 in that particular dataset

                # melt'ing
                df_long = dfs[
                    ['report', 'R365', 'G365', 'B365', 'R445', 'G445', 'B445', 'R525', 'G525', 'B525', 'R590', 'G590',
                     'B590', 'R645', 'G645', 'B645']].set_index('report').stack().reset_index()
                df_long.columns = ['report', 'channel', 'intensity']

                fig = px.box(
                    data_frame=df_long,
                    y='intensity',
                    x='channel',
                    color='report'
                )

                fig.update_layout(
                    title_text=spot_name,
                    title_font_size=30,
                    font=dict(
                        size=18,
                    )
                )

bio/dashboard/templates/dashboard/device_detail.html
{% extends "base.html" %}

{% block content %}

<br>
  <h1>Device: {{ device.name }} </h1><br>

  <h3>Associated runs:</h3><br>


    <a href="{{ run.get_absolute_url }}">{{ run.name }}</a><br>


    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Date</th>
          <th scope="col">Name</th>
          <th scope="col">Notes</th>
        </tr>
      </thead>
      <tbody>
      {% for run in device.run_set.all|dictsortreversed:"name" %}
        <tr>
          <th scope="row">{{run.id}}</th>
          <td>{{ run.started_at }}</td>
          <td><a href="{{ run.get_absolute_url }}"> {{ run.name }} </a></td>
          <td>{{ run.notes }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>



{% endblock %}

bio/dashboard/templates/dashboard/device_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Device List</h1>

  {% if device_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Created at</th>
          <th scope="col">Name</th>
          <th scope="col">RunCounter</th>
          <th scope="col">Storage</th>
          <th scope="col">Filter</th>
          <th scope="col">TempSensor</th>
          <th scope="col">CPUID</th>
          <th scope="col">IP</th>
          <th scope="col">Notes</th>
        </tr>
      </thead>
      <tbody>
        {% for device in device_list %}
        <tr>
          <th scope="row">{{device.id}}</th>
          <td>{{ device.created_at }}</td>
          <td><a href="{{ device.get_absolute_url }}"> {{ device.name }} </a></td>
          <td>{{ device.run_set.all|length }}</td>
          <td>{{ device.storage }}</td>
          <td>{{ device.filter }}</td>
          <td>{{ device.tempsensor }}</td>
          <td>{{ device.serial_number }}</td>
          <td>{{ device.ip }}</td>
          <td>{{ device.notes }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no devices in the database.</p>
  {% endif %}

{% endblock %}

bio/dashboard/templates/dashboard/report_detail.html
{% extends "base.html" %}
{% load tz %}
{% block content %}
    {% load static %}



<h1>Report: {{ report.name }} </h1><br>
{% get_current_timezone as TIME_ZONE %}
<h3>Created: {{ report.created_at }}  </h3>{{ TIME_ZONE }}<br>

<br>
<br>
Device:     <a href="{{ report.run.device.get_absolute_url }}">{{ report.run.device.name }}</a>  <br>
Run:        <a href="{{ report.run.get_absolute_url }}">{{ report.run.name }}</a>  <br>
Location:   <a href="{% static report.path %}">{{ report.path }}</a>  <br>


<br>
<!--
<h2>Test: Create triangle plot, in development</h2><br>
<form action="{% url 'dashboard:test' report.run.id %}" method="post">
    {% csrf_token %}
    <label for="example">Generate triangle graph for runId: </label>
    <input id="example" type="text" name="example" value="{{ report.run.id }}"><br>

    {% with list='R365 G365 B365 R445 G445 B445 R525 G525 B525 R590 G590 B590 R645 G645 B645' %}
    {% for channel in list.split %}
        <input type="checkbox" id={{channel}} name={{channel}} value={{channel}}x checked>
        <label for={{channel}}>{{channel}}&emsp;</label>
                {% if forloop.counter|divisibleby:3 %}
    <br>
    {% endif %}

    {% endfor %}
    {% endwith %}

  <label for="roiset">Choose a roiset:</label>
  <select name="roiset" id="roiset">
    <option value="RoiSet1.zip">RoiSet1.zip</option>
    <option value="RoiSet2.zip">RoiSet2.zip</option>
    <option value="RoiSet3.zip">RoiSet3.zip</option>
    <option value="RoiSet4.zip">RoiSet4.zip</option>
  </select>


    <input type="submit" value="Generate">
</form>
-->

<br>
<br>
<br>
{% autoescape off %}

{% if not basecalls.empty %}
<div>
    <h3>Basecalls :</h3> <br>
    {{ basecalls|safe }}
</div>
{% endif %}

{% if not read_length_histogram.empty %}
<div>
    <h3>Read-length histogram of perfect reads</h3> <br>
    {{ read_length_histogram }}
</div>
{% endif %}

{% if not quality_score_graph.empty %}
<div>
    <h3>Quality scores</h3> <br>
    {{ quality_score_graph }}
</div>
{% endif %}

{% if bar_plot %}
<div>
    <h3>15D to 4D Spot intensities with basecalls:</h3> <br>
    {{ bar_plot }}
</div>
{% endif %}

{% if df_metrics %}
<div>
    <h3>Metrics table :</h3> <br>
    {{ df_metrics }}
</div>
{% endif %}

{% if spot_intensities_vs_time %}
<div>
    <h3>15D Spot intensities :</h3> <br>
    {% for plot in spot_intensities_vs_time %}

        {{ plot }}

    {% endfor %}
</div>
{% endif %}

{% if triangle_plot %}
<div>
    <br>
    <h3>Cycle 1, Spot intensities projected on 2-dimensional color channels.</h3> <br>
    {{ triangle_plot }}
</div>
{% endif %}

{% if spot_trajectories_plot %}
<div>
    <br>
    <h3>Spot intensity trajectories. All cycles.</h3> <br>
    {{ spot_trajectories_plot }}
</div>
{% endif %}

{% endautoescape %}


<h3>Analysis:</h3><br>
{% if analysis_filenames %}
    <div>
        {% for img in analysis_filenames %}
            {% if forloop.counter0|divisibleby:4 %}
            <div class="row">
            {% endif %}
                <div style="float:left; width:400px; height:350px;">
                {{img.0}}
                <a href="{% static img.1 %}"><img src="{% static img.1 %}" class="img-thumbnail" alt="{% static img.1 %}"></a>
                </div>
            {% if forloop.counter|divisibleby:4 %}
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% else %}
    <p>Analysis not found.</p>
{% endif %}



{% endblock %}

bio/dashboard/templates/dashboard/report_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Report List</h1>

  {% if report_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Created at</th>
          <th scope="col">Report</th>
          <th scope="col">Run</th>
          <th scope="col">Device</th>
          <th scope="col">User</th>
        </tr>
      </thead>
      <tbody>
        {% for report in report_list %}
        <tr>
          <th scope="row">{{report.id}}</th>
          <td>{{ report.created_at }}</td>
          <td><a href="{{ report.get_absolute_url }}"> {{ report.name }} </a></td>
          <td><a href="{{ report.run.get_absolute_url }}">{{ report.run.name }}</a></td>
          <td><a href="{{ report.run.device.get_absolute_url }}">{{ report.run.device.name }}</a></td>
          <td> {{ report.user.username }} </a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no reports in the database.</p>
  {% endif %}

{% endblock %}

bio/dashboard/templates/dashboard/reservoir_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Reservoir List</h1>

  {% if reservoir_list %}
    <table class="table table-striped table-hover text-nowrap">
      <thead>
        <tr>
<!--          <th scope="col">#</th> -->
<!--          <th scope="col">Created_at</th> -->
          <th scope="col">Assembly Date</th>
          <th scope="col">Serial Number</th>
          <th scope="col">Vendor</th>
          <th scope="col">Substrate</th>
          <th scope="col">Cleaning</th>
          <th scope="col">Coating</th>
          <th scope="col">Functionalization</th>
          <th scope="col">SpotLayout</th>
          <th scope="col">Blocking</th>
          <th scope="col">Run</th>
        </tr>
      </thead>
      <tbody>
        {% for reservoir in reservoir_list %}
        <tr>
<!--          <th scope="row">{{reservoir.id}}</th> -->
<!--          <td>{{ reservoir.created_at }}</td> -->
          <td>{{ reservoir.assembly_date }}</td>
          <td>{{ reservoir.serial_number }}</td>
          <td>{{ reservoir.vendor }}</td>
          <td>{{ reservoir.substrate }}</td>
          <td>{{ reservoir.cleaning }}</td>
          <td>{{ reservoir.coating }}</td>
          <td>{{ reservoir.functionalization }}</td>
          <td>{{ reservoir.library }}</td>
          <td>{{ reservoir.blocking }}</td>
          <td>
          {% for run in reservoir.run_set.all %}
            <a href="{{ run.get_absolute_url }}">{{ run.name }},</a>
          {% endfor %}
          </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no reservoirs in the database.</p>
  {% endif %}
{% endblock %}

bio/dashboard/templates/dashboard/run_detail.html
{% extends "base.html" %}

{% block content %}
    {% load static %}

<h3></h3><br>

<div class="card">
  <div class="card-header">
    <h1>Run: {{ run.name }}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Device: <a href="{{ run.device.get_absolute_url }}">{{ run.device.name }}</a></h5>
    <p class="card-text">Reservoir: <a href="{% url 'dashboard:reservoirs' %}">{{ run.reservoir }}</a>  </p>
    <p class="card-text">Started: {{ run.started_at }} </p>
    <p class="card-text">Ended: {{ run.ended_at }} </p>
    <p class="card-text">Operator: {{ run.operator }} </p>
    <p class="card-text">Sequencing Protocol: {{ run.sequencing_protocol }} </p>
    <p class="card-text">Notes: {{ run.notes }} </p>
    <p> Location: <a href="{% static run.path %}">{{ run.path }}</a> </p>
  </div>
</div>
<br>
<br>


<h3>Create new report:</h3><br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
</form>


<br>
<h3>Reports:</h3><br>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Created at</th>
        <th scope="col">Name</th>
        <th scope="col">#reads</th>
        <th scope="col">Quality ...</th>
      </tr>
    </thead>
    <tbody>
    {% for report in run.report_set.all %}
    <tr>
      <td>{{ report.created_at }}</td>
      <td><a href="{{ report.get_absolute_url }}">{{ report.name }}</a></td>
      <td></td>
      <td></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
<br>
<br>

{% if raw_tif %}
<h3>Raw:</h3><br>
    <div>
        <!-- 0 and 1 are tuple numbers -->
        {% for img in raw_tif %}
    <div style="float:left; width:400px; height:350px;">
        {{img.0}}
        <img src="{% static img.1 %}" class="img-thumbnail" alt="{% static img.1 %}">
    </div>
        {% endfor %}
</div>
{% else %}
<!--
    <p>Raw files not found.</p>
-->
{% endif %}

{% if raw_thumbnails %}
<h3>Thumbnails:</h3><br>
    <div>
        <!-- 0 and 1 are tuple numbers -->
        {% for img in raw_thumbnails %}
    <div style="float:left; width:400px; height:350px;">
        {{img.0}}
        <img src="{% static img.1 %}" class="img-thumbnail" alt="{% static img.1 %}">
    </div>
        {% endfor %}
</div>
{% else %}
<!--
    <p>Thumbnails not found.</p>
-->
{% endif %}



{% endblock %}

bio/dashboard/templates/dashboard/run_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Run List</h1>

  {% if run_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Started_at</th>
          <th scope="col">Run</th>
          <th scope="col">Device</th>
          <th scope="col">Reservoir</th>
          <th scope="col">Operator</th>
          <th scope="col">Sequencing-Protocol</th>
          <th scope="col">Notes</th>
        </tr>
      </thead>
      <tbody>
        {% for run in run_list %}
        <tr>
          <th scope="row">{{run.id}}</th>
          <td>{{ run.started_at }}</td>
          <td><a href="{{ run.get_absolute_url }}"> {{ run.name }} </a></td>
          <td>{{ run.device.name }}</td>
          <td><a href="{% url 'dashboard:reservoirs' %}">{{ run.reservoir }}</a></td>
          <td>{{ run.operator }}</td>
          <td>{{ run.sequencing_protocol }}</td>
          <td>{{ run.notes }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no runs in the database.</p>
  {% endif %}
{% endblock %}