bio/bio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("dashboard.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

bio/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path('', views.home, name="home"),
    path('logout', views.logout_view, name='logout'),
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('runs/', views.RunListView.as_view(), name='runs'),
    path('reports/', views.ReportListView.as_view(), name='reports'),
    path('reservoirs', views.ReservoirListView.as_view(), name='reservoirs'),
    path('compare_runs', views.compare_runs, name='compare_runs'),
    path('device/<int:pk>', views.DeviceDetailView.as_view(), name='device-detail'),
    path('run/<int:pk>', views.RunDetailView.as_view(), name='run-detail'),
    path('report/<int:pk>', views.ReportDetailView.as_view(), name='report-detail'),
    path('<int:run_id>/test/', views.test, name="test"),
]

bio/dashboard/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Device(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    serial_number = models.CharField(max_length=20)
    storage = models.CharField(max_length=30, null=True, blank=True)
    notes = models.CharField(max_length=30, null=True, blank=True)
    ip = models.CharField(max_length=40, null=True, blank=True)
    filter = models.CharField(max_length=40, null=True, blank=True)
    tempsensor = models.CharField(max_length=40, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('dashboard:device-detail', args=[str(self.id)])

    def __str__(self):
        return self.name + " " + self.serial_number


class Reservoir(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    assembly_date = models.DateField(null=True, blank=True)
    serial_number = models.IntegerField(null=False, unique=True)
    vendor = models.CharField(max_length=200)
    substrate = models.CharField(max_length=200)
    cleaning = models.CharField(max_length=200)
    coating = models.CharField(max_length=200)
    functionalization = models.CharField(max_length=200)
    library = models.CharField(max_length=200)
    blocking = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('dashboard:reservoir-detail', args=[str(self.id)])

    def __str__(self):
        return str(f"{self.serial_number} {self.substrate} {self.functionalization} {self.library}")


class Run(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, unique=True)
    device = models.ForeignKey(Device, null=True, blank=True, on_delete=models.SET_NULL)
    operator = models.CharField(max_length=50, null=True, blank=True)
    sequencing_protocol = models.CharField(max_length=100, null=True, blank=True)
    path = models.CharField(max_length=200, null=True)
    started_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=400, null=True, blank=True)
    reservoir = models.ForeignKey(Reservoir, null=True, blank=True, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('dashboard:run-detail', args=[str(self.id)])

    def __str__(self):
        return self.name



class Report(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    run = models.ForeignKey(Run, null=True, blank=True, on_delete=models.SET_NULL)
    path = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
    )

    def get_absolute_url(self):
        return reverse('dashboard:report-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

bio/dashboard/forms.py
from django import forms
from .models import Report


class RoiSetForm(forms.Form):
    title = forms.CharField(label='Label', max_length=50)
    file = forms.FileField(label='RoiSet File')


class ExampleModelForm(forms.Form):
    report1 = forms.ModelChoiceField(
        label="Report 1",
        queryset = Report.objects.all(),
        required=True
    )

    report2 = forms.ModelChoiceField(
        label="Report 2",
        queryset = Report.objects.all(),
        required=False
    )

    report3 = forms.ModelChoiceField(
        label="Report 3",
        queryset = Report.objects.all(),
        required=False
    )

    report4 = forms.ModelChoiceField(
        label="Report 4",
        queryset = Report.objects.all(),
        required=False
    )

    report5 = forms.ModelChoiceField(
        label="Report 5",
        queryset = Report.objects.all(),
        required=False
    )

    report6 = forms.ModelChoiceField(
        label="Report 6",
        queryset = Report.objects.all(),
        required=False
    )

bio/dashboard/views.py
from typing import List, AnyStr

from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

from django.http import HttpResponse
from django.views import generic
from .models import Device, Run, Report, Reservoir
import pandas as pd
from plotly.offline import plot
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import os
import glob
import math
from itertools import product
import ziontools
from sklearn import linear_model
import cv2 as cv
from scipy import ndimage
import roifile
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import re
from datetime import datetime, timedelta
from django.utils import timezone
import dateutil.parser
from .tasks import run_pixel_extraction, mul
from .forms import RoiSetForm, ExampleModelForm
import itertools

from django.http import HttpResponseRedirect
from django.urls import reverse

# TODO, move to configuration
data_root_path = "/static_root/InstrumentData"
sequencing_file = '/tmp/Sequencing.csv'
reservoir_file = '/tmp/Reservoir_Inventory.csv'




def extract_datetime(subfolderstr: str) -> str | None:
    """TODO timestamp needs to be provided in iso format instead of being extracted from folder name"""
    match = re.search(r'^(20\d{2})(\d{2})(\d{2})_(\d{2})(\d{2})', subfolderstr)

    if not match:
        print(f'unable to extract datetime from {subfolderstr}')
        return None

    # print(type(match))
    # print(match.groups())
    # print(match.group(0))

    datetime_str = match.group(0)  # 20230612_1145
    datetime_object = datetime.strptime(datetime_str, '%Y%m%d_%H%M')
    # print(datetime_object) # 2023-06-12 11:45:00

    aware_start_time = timezone.make_aware(datetime_object)  # aware

    return aware_start_time


def update_run_start_date():

    runs = Run.objects.all()
    for run in runs:
        if not run.started_at:
            d = extract_datetime(run.name)
            if d:
                run.started_at = d
                run.save()


def import_signup_sheet():

    if not os.path.exists(sequencing_file):
        print(f"{sequencing_file} not found")
        return

    df = pd.read_csv(sequencing_file)
    # drop rows that are fully empty
    df.dropna(how="all", inplace=True)

    for index, row in df.iterrows():
        print(row)

        # search runs for Seq ID
        # filter out QC
        # check if transformer matches, if not print error
        # update reservoir if not set, print error if different
        # add to notes: Scientist	Seq Ctrl Program	Description	Deviations

        runs = Run.objects.filter(name__contains=row['Seq ID'])

        # update() only works on querysets,
        if runs:
            print("type of run", type(runs))
            runs.update(notes=row['Description'])
            runs.update(operator=row['Scientist'])
            runs.update(sequencing_protocol=row['Seq Ctrl Program'])
            match = re.search("^R(\d{1,4})$", str(row['Reservoir']))
            if match:
                reservoir_sn = int(match.group(1))
            else:
                print(f"skip {row['Reservoir']}")
                continue
            reservoir = Reservoir.objects.filter(serial_number=reservoir_sn)
            print('received object', reservoir)
            if reservoir:
                print('run update')
                runs.update(reservoir=reservoir[0])  # TODO, make sure it is unique


def import_reservoirs_from_csv():

    if not os.path.exists(reservoir_file):
        print(f"{reservoir_file} not found")
        return

    df = pd.read_csv(reservoir_file)

    # show bad entries
    #df.dropna(subset=['Unnamed: 16'])

    # drop unnamed columns
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # drop rows that are fully empty
    df.dropna(how="all", inplace=True)

    '''
    created_at = models.DateTimeField(auto_now_add=True)
    serial_number = models.IntegerField(null=False, unique=True)
    vendor = models.CharField(max_length=200)
    substrate = models.CharField(max_length=200)
    cleaning = models.CharField(max_length=200)
    coating = models.CharField(max_length=200)
    functionalization = models.CharField(max_length=200)
    library = models.CharField(max_length=200)
    blocking = models.CharField(max_length=200)
    '''

    for index, row in df.iterrows():
        print(row)

        reservoir_sn = int(row['ID'])

        assembly_date = None
#        print(f"date: {row['Assembly Date']} type: {type(row['Assembly Date'])}")
        if isinstance(row['Assembly Date'], float):
            print(f"skip reservoir {reservoir_sn}, assembly_date is float: {row['Assembly Date']}")
        else:
            assembly_date = dateutil.parser.parse(row['Assembly Date'])

        reservoirs = Reservoir.objects.filter(serial_number=reservoir_sn)
        if reservoirs.exists():
#            reservoirs.update(assembly_date=assembly_date)
            continue

        r = Reservoir(
            assembly_date=assembly_date,
            serial_number=reservoir_sn,
            vendor=row['Slide Vendor'],
            substrate=row['Substrate'],
            cleaning=row['Cleaning'],
            coating=row['Coating'],
            functionalization=row['Functionalization'],
            library=row['SpotLayout#']
#            blocking=models.CharField(max_length=200)
        )
        r.save()


def scan():

    if not os.path.isdir(data_root_path):
        print(f"error with: {data_root_path}")
        return

    devices = Device.objects.all()

    for dev in devices:
        print(dev.name)

        raw_device_path = os.path.join(data_root_path, dev.name)
        if os.path.isdir(raw_device_path):

            subfolders: list[AnyStr] = [f.path for f in os.scandir(raw_device_path) if f.is_dir()]

            for subfolder in subfolders:
                run_directory = os.path.basename(subfolder)
                print(run_directory)

                # guess number of cycles:
                prot_file_names = sorted(glob.glob(subfolder + "/*Protocol*", recursive=False))
                if prot_file_names:
                    print(prot_file_names[-1])

                if Run.objects.filter(name=run_directory).exists():
                    # run exists already
                    continue

                # extract date from subfolder, TODO, should be in a json file, in ISO format
                started_at = extract_datetime(run_directory)

                r = Run(
                    name=run_directory,
                    device=Device.objects.get(name=dev.name),
                    path=subfolder.lstrip('/static_root'),
                    started_at=started_at,
#                    notes="test",
#                    reservoir=Reservoir.objects.get(serial_number=366),
                )
                print(f"Create new run {r}")
                r.save()

    '''

    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)
    device = models.ForeignKey(Device, null=True, blank=True, on_delete=models.SET_NULL)
    path = models.CharField(max_length=200, null=True)
    started_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    notes = models.CharField(max_length=400, null=True)
    reservoir = models.ForeignKey(Reservoir, null=True, blank=True, on_delete=models.SET_NULL)

    '''

@login_required
def home(request):
    devices = Device.objects.all()

    scan()
#    update_run_start_date()
#    import_reservoirs_from_csv()
    import_signup_sheet()

    run_histogram = create_run_histogram()
    return render(request, 'home.html', {'devices': devices, 'run_histogram': run_histogram})


def logout_view(request):
    logout(request)
    return redirect('dashboard:home')


@login_required
def compare_runs(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = ExampleModelForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            df_reports = {}

            for i in range(1, 7):
                report = form.cleaned_data["report"+str(i)]
                if not report:
                    continue
                report_full_path = os.path.join("/static_root", report.path)
                spot_data_csv = os.path.join(report_full_path, 'spot_pixel_data.csv')
                if os.path.exists(spot_data_csv):
                    df_i = pd.read_csv(spot_data_csv)
                    df_reports[report.name] = df_i

            df = pd.concat(df_reports).reset_index()
            df.rename(columns={'level_0': 'report', 'level_1': 'old_index'}, inplace=True)

            plots = []
            # for all spot names:
            for spot_name in df.spot_name.unique():
                dfs = df.loc[(df['spot_name'] == spot_name) & (df['cycle'] == 1)] # cycle check may not be necessary, always cycle 1 in that particular dataset

                # melt'ing
                df_long = dfs[
                    ['report', 'R365', 'G365', 'B365', 'R445', 'G445', 'B445', 'R525', 'G525', 'B525', 'R590', 'G590',
                     'B590', 'R645', 'G645', 'B645']].set_index('report').stack().reset_index()
                df_long.columns = ['report', 'channel', 'intensity']

                fig = px.box(
                    data_frame=df_long,
                    y='intensity',
                    x='channel',
                    color='report'
                )

                fig.update_layout(
                    title_text=spot_name,
                    title_font_size=30,
                    font=dict(
                        size=18,
                    )
                )

bio/dashboard/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>454 Bio Run Browser</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
  {% include 'header.html' %}

  <div class="container-fluid" style="width: 90%";>
  {% block content %}
  {% endblock %}
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

bio/dashboard/templates/compare_runs.html
{% extends "base.html" %}

{% block content %}

<h2>
    Cycle-1 ROI comparison.
</h2>

{% if form %}
<div>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
</div>
{% endif %}


{% autoescape off %}
{% for plot in plots %}
    {{ plot }}
{% endfor %}

{% endautoescape %}

{% endblock %}

bio/dashboard/templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
      {% load static %}
      <img src="{% static '454biologo.svg' %}" alt="454 logo" style="width:100px;height:100px;" />
    <a class="navbar-brand" href="{% url 'dashboard:home' %}">454 Bio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-3 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'dashboard:devices' %}">Devices</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:runs' %}">Runs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:reports' %}">Reports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:reservoirs' %}">Reservoirs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:compare_runs' %}">Compare-Runs</a>
        </li>
        <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        -->
      </ul>
      {% load socialaccount %}
      {% if user.is_authenticated %}
      <p> {{ user.username }} {{ user.email }}</p>
      <a href="{% url 'dashboard:logout' %} ">Logout</a>
      {% endif %}
    </div>
  </div>
</nav>

bio/dashboard/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

<h3>Google Drive links:</h3>
<a href="https://docs.google.com/spreadsheets/d/1Xnab1EE8xHKLXboeUNA82PFBL_ItH5wr/">Sequencing Runs</a><br>
<a href="https://docs.google.com/spreadsheets/d/1z7_0Mjxd9BTmZRJI15hiKi5fVlU1JHv8t-9TplfPahw/">Reservoir Inventory</a><br>
<a href="https://drive.google.com/drive/u/1/folders/1HEI9Z7xFajdcYTWHsZfglBNvy_YN_VKI">Spotter Protocols</a><br>
<a href="https://drive.google.com/drive/u/1/folders/1vG0Y19W8qCHMh8DiLIOgsDof1E8-jVHv">Onepot Protocols</a><br>



{% if run_histogram %}
{% autoescape off %}
<div>
    <h1>Weekly runs:</h1> <br>
    {{ run_histogram }}
</div>
{% endautoescape %}
{% endif %}


{% endblock %}

bio/dashboard/templates/test.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

{{ req }}
{{ post }}

{% endblock %}